language: go
go:
- 1.8
- tip
env:
- GIMME_OS=linux GIMME_ARCH=amd64 ENV="dev"
install:
- dep ensure
script: make test
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: EPCTH7DndhWbFugtb5lNmBn1gkrAIuYCqrIMp7OvZ8FuuRtNeJp99q60HP8kAayFDRCKsk8hRmIZJeEGVbHFvmWl1Xnz5q7oXi0VNY2gEAKyQHp8NP9F/8dRN2d/1wZgBOx0KZuDxUjvZcBDagA4UyvYAh93abR/wb1sWTDkC9Z6ooxCvFZIlaLGWvzE5DtRx1vlw6QMf1EPqvUabpcdsDLIajTOr5XpHuPP8kXyaJcZrBLzJG0v3CF+ajfBcF91Npd8TZxHHTOSyxk6qkKwwhHD68bD8DiF+FSCYPE2gwOg05CsjS/XWT4A6jmMDycpo2K7n4Qgk6CE8AnpOAc6eX1Bu6btzGQnQJas6ssRAnus7h1ZOF8iauyrHTWw8QIkXX35VCIdaEj/5Zcl9rJ5Tka4wNYtoL5oUWmOtLJVtB+ai1FipKpRaXJRhbA1/1TfsaIKmH98MWjDBXjDrvKRVSxbqU1JdbLyBmEqDQ37WBQmFv6/ukABeWwkSiGfveTA0xuumHvmd4PwOF8MWwndmQ79Fr+JJGJ++u83Ki/iCc7xfTPcmxsXpWskNgPs4bskSQ62osxosJ4eX6Sbu/0BLnenPhMQIUDxjwb56tjqMBTQTxnaUeNZ0iEA/xRdNo/Da5Iyha2R/aT6apP6d6kOylp7b9WH3RMnNjwNziaLwZM=
matrix:
  allow_failures:
  - go: tip
deploy:
  provider: gae
  keyfile: service-account.json
  project: afanty-170802
before_install:
- openssl aes-256-cbc -K $encrypted_3cafb6aa6063_key -iv $encrypted_3cafb6aa6063_iv
  -in afanty-key.json.enc -out service-account.json -d
- go get github.com/golang/dep/...
